config/routes.rb
MasterbetApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/results', to: 'static_pages#results', via: 'get'
  match '/tzakpot', to: 'static_pages#tzakpot', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/tips', to: 'static_pages#tips', via: 'get'
  match '/galery', to: 'static_pages#galery', via: 'get'
  match '/lucky', to: 'static_pages#lucky', via: 'get'
  match '/news', to: 'static_pages#news', via: 'get'
  match '/myshop', to: 'static_pages#myshop', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  root 'static_pages#home'
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Η φόρμα που συμπληρώσατε έχει <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div class="container marketing">
	<h3>Ειδήσεις και Events - <span class="text-muted">Μόνο από το πρακτορείο μας για έξυπνους παίχτες.</span></h3>
	<% if @feed_items.any? %>
  		<ul class="microposts">
    	<%= render partial: 'shared/feed_item', collection: @feed_items %>
  		</ul>
  		<%= will_paginate @feed_items %>
	<% end %>
</div>

app/views/shared/_feed_item.html.erb

<li align=left id="<%= feed_item.id %>" class="feed">
  
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-xs-6 .col-md-4">
          
    <% if feed_item.content != nil %>
      <h3><div class="content"><%= wrap(feed_item.content) %></div></h3>
    <% end %>

    <% if feed_item.text != nil %>
      <div class="content"><%= wrap(feed_item.text) %></div>  
    <% end %>
    </div>
    <div class="col-xs-6 .col-md-4">
    <% if feed_item.image_url != nil %>
      <img class="avatar" src=<%= feed_item.image_url(:thumb).to_s %> alt="Avatar">
    <% end %>
    <div class="row" class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    
    <% if current_user?(feed_item.user) %>
      <%= link_to "Διαγραφή σχολίου", feed_item, method: :delete,
              data: { confirm: "Είστε σίγουρος για την διαγραφή του σχολίου;" },
          title: feed_item.content %>
       <%= link_to "Επεξεργασία σχολίου", edit_micropost_path(feed_item) %>
    <% end %>
    </div>
  </div>
  </div>
</li>

app/views/shared/_gallery_feed.html.erb
<% if @feed_items.any? %>
  <ul class="microposts">
    <%= render partial: 'shared/gallery_feed_item', collection: @feed_items %>
  </ul>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_gallery_feed_item.html.erb

<li align=left id="<%= gallery_feed_item.id %>" class="feed">
  
  <hr class="featurette-divider">
  <div class="col-6 col-sm-6 col-lg-4">

    <% if gallery_feed_item.image_url != nil %>
      <a href="<%= gallery_feed_item.image_url.to_s %>" title="Masterbet" data-gallery>
        <img src="<%= gallery_feed_item.image_url(:thumb).to_s %>" alt="Masterbet">
      </a>
      
    <% end %>
    <% if current_user?(gallery_feed_item.user) %>
      <%= link_to "Διαγραφή εικόνας", gallery_feed_item, method: :delete,
              data: { confirm: "Είστε σίγουρος για την διαγραφή του σχολίου;" },
          title: gallery_feed_item.content %>
    <% end %>
    </div>
</li>

app/views/shared/_lucky_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/lucky_feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_lucky_feed_item.html.erb
<% if lucky_feed_item.category == "lucky" %>

  <li align=left id="<%= lucky_feed_item.id %>" class="feed">
    <div  hidden class="content"><%= lucky_feed_item.content %></div>  
      <% if lucky_feed_item.image_url != nil %>
        <img hidden class="avatar" src=<%= lucky_feed_item.image_url(:thumb).to_s %> alt="Avatar">
        <img hidden class="logogif" src="/assets/loading.gif" alt="Logogif">
        
        <canvas class="myCanvas" id="myCanvas" width="400" height="200" style="border:1px "></canvas>
            
        <img id="canvasImg" alt="Right click to save me!">
    
      <% end %>
      <span class="timestamp">
        Posted <%= time_ago_in_words(lucky_feed_item.created_at) %> ago.
      </span>
      <% if current_user?(lucky_feed_item.user) %>
        <%= link_to "Διαγραφή σχολίου", lucky_feed_item, method: :delete,
                                     data: { confirm: "Είστε σίγουρος για την διαγραφή του σχολίου;" },
                                     title: lucky_feed_item.content %>
      <% end %>

  </li>

  <% end %>

app/views/shared/_micropost_form.html.erb

<%= form_for @micropost, :html => {:multipart => true} do |f| %>
  
  <%= render 'shared/error_messages', object: f.object %>
  <p>
  <div class="field">
    <%= f.text_area :content, :cols => "30", :rows => "1", placeholder: "Εισάγετε τίτλο για το άρθρο σας..." %>
  </div></p>
  <p>
  <div class="field">
  <%= f.text_area :text, :cols => "40", :rows => "8", class: "tinymce", placeholder: "Εισάγετε κείμενο για το άρθρο σας..." %>
  </div></p>
  <div class="field">
  <p>
  	<strong>Εισαγωγή εικόνας: </strong><%= f.file_field :image %>
  </p>
  </div>
  <div class="field">	
  	<p>Κατηγορία Δημοσίευσης:
  	<%= f.select :category, [['Ειδήσεις','news'],['Events','events'],['Blog','blog']] %></p>
  </div>
  
  <%= f.submit "Δημοσίευση", class: "btn btn-large btn-primary" %>
  <%= f.submit 'Άδειασε την Φόρμα', :type => 'reset', class: "btn btn-small btn-primary" %>
<% end %>
<%= tinymce :theme => "modern", :language => "el", :entity_encoding => "raw" %>  

app/views/shared/_tips_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/tips_feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_tips_feed_item.html.erb
<% if tips_feed_item.category == "tips" %>

  <li align=left id="<%= tips_feed_item.id %>" class="feed">
    <div class="content"><%= tips_feed_item.text %></div> 
    <div class="content"><table class="table">
            <thead>
              <tr>
                <th>Προγνωστικό</th>
                <th>Αριθμός Αγώνα</th>
                <th>Αγώνας</th>
                <th>Ώρα</th>
                <th>Επιτυχία</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= tips_feed_item.content %></td>
                <td>32</td>
                <td>Ολυμπιακός-Παναθηναικός</td>
                <td>25/4/14 21:00μμ</td>
                <td bgcolor="green"><span class="glyphicon glyphicon-ok"></span></td>
              </tr>
            </tbody>
          </table> 
      </div> 
      <span class="timestamp">
        Posted <%= time_ago_in_words(tips_feed_item.created_at) %> ago.
      </span>
      <% if current_user?(tips_feed_item.user) %>
        <%= link_to "Διαγραφή σχολίου", tips_feed_item, method: :delete,
                                     data: { confirm: "Είστε σίγουρος για την διαγραφή του σχολίου;" },
                                     title: tips_feed_item.content %>
      <% end %>

  </li>

  <% end %>

app/views/shared/_user_info.html.erb


<h1>
  Καλώς ήρθες <%= current_user.name %>
</h1>

<span>
  <% current_user.email %><%= link_to "Ο Λογαριασμός μου", current_user %>
</span>
<span>
  Σύνολο σχολίων <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_user_show.html.erb
<% provide(:title, @user.name ) %>
<div class="form-signin">
<div class="top">
	<h1><%= @user.name %></h1> 
	<%= @user.email %>
	<div class="span8">
    	<% if @user.microposts.any? %>
      		<h3>Microposts (<%= @user.microposts.count %>)</h3>
      		<ol class="microposts">
        	<%= render @microposts %>
      		</ol>
      		<%= will_paginate @microposts %>
    	<% end %>
  	</div>
    <% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center hero-unit">
    <%= link_to "Γραφτείτε για να συμμετάσχετε!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>
</div>
</div>