config/routes.rb
MasterbetApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/results', to: 'static_pages#results', via: 'get'
  match '/tzakpot', to: 'static_pages#tzakpot', via: 'get'
  match '/blog', to: 'static_pages#blog', via: 'get'
  match '/tips', to: 'static_pages#tips', via: 'get'
  match '/galery', to: 'static_pages#galery', via: 'get'
  match '/lucky', to: 'static_pages#lucky', via: 'get'
  match '/news', to: 'static_pages#news', via: 'get'
  match '/myshop', to: 'static_pages#myshop', via: 'get'
  match '/events', to: 'static_pages#events', via: 'get'
  root 'static_pages#home'
  

end

app/views/layouts/_carousel.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li class="" data-target="#myCarousel" data-slide-to="1"></li>
        <li class="active" data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item">
          <%= link_to image_tag("Football-Bet4.jpg", alt: "Rails"), signup_path %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Γίνε Μέλος Σήμερα</h1>
              <p>Της μεγαλύτερης κοινότητας πρακτορείων ΟΠΑΠ στην Ελλάδα</p>
              <p><%= link_to "Εγγραφείτε σήμερα!", signup_path, class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
        <div class="item">
          <%= link_to image_tag("Football-Bet1.jpg", alt: "Rails"), galery_path %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Νέα-Ειδήσεις</h1>
              <p>Τα πάντα για το στοίχημα και τα παιχνίδια του ΟΠΑΠ</p>
              <p><%= link_to "Νέα-Ειδήσεις", news_path, class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
        <div class="item active">
          <%= link_to image_tag("Football-Bet2.jpg", alt: "Rails"), galery_path %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Το Πρακτορείο μας!</h1>
              <p>Ζωντανή περιήγηση, φωτογραφίες και άλλα πολλά...</p>
              <p><%= link_to "Οι Φωτογραφίες μας", galery_path, class: "btn btn-lg btn-primary" %></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.masterbet.gr/">MasterBet Application</a>
    από τον Γιάννη Κουμούτσο
  </small>
  <p class="pull-right"><a href="#">Back to top</a></p>
</footer>

app/views/layouts/_navbar.html.erb
    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Π.Ντόμαλης",    root_path, class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Το Πρακτορείο μου <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Περιγραφή-Εικόνα 360",    myshop_path %></li>
                    <li><%= link_to "Εικόνες",    galery_path %></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Παιχνίδια ΟΠΑΠ<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Αποτελέσματα",    results_path %></li>
                    <li><%= link_to "Τζακποτ",    tzakpot_path %></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Νέα<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Προγνωστικά",    tips_path %></li>
                    <li><%= link_to "Κέρδη",    lucky_path %></li>
                    <li><%= link_to "Ειδήσεις",    news_path %></li>
                    <li><%= link_to "Events",    events_path %></li>
                  </ul>
                </li>
                <li><%= link_to "Blog",    blog_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Επικοινωνία <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Κατάστημα",    myshop_path %></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Γίνε Μέλος!</li>
                    <li><%= link_to "Έγγραφή Χρήστη",    signup_path %></li>
                    <li><%= link_to "Είσοδος Χρήστη",    signin_path %></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav pull-right">
                <% if signed_in? %>
                <% @user=current_user %>
                <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Λογαριασμός Χρήστη <%= @user.name %><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Ο Λογιαριασμός μου", user_path(current_user) %></li>
                  <li><%= link_to "Ρυθμίσεις Λογιαριασμού", edit_user_path(current_user) %></li>
                  <li><%= link_to "Χρήστες Σελίδας", users_path %></li>
                  <li class="divider"></li>
                  <li>
                  <%= link_to "Έξοδος Χρήστη", signout_path, method: "delete" %>
                  </li>
                </ul>
                </li>
                <% else %>
                <li><%= link_to "Είσοδος Χρήστη", signin_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/_threecolumn.html.erb
<!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
        <%= link_to image_tag("results.jpg", alt: "Rails"), 'myshop' %>
          <h2>Εικόνα 360</h2>
          <p>Δείτε κάθε γωνιά του ανανεωμένου Πρακτορείου μας.</p>
          <p><%= link_to "Λεπτομέρειες »", myshop_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= link_to image_tag("results2.jpg", alt: "Rails"), 'lucky' %>
          <h2>Κέρδη-Επιτυχίες</h2>
          <p>Κείμενο για Κέρδη-Επιτυχίες.</p>
          <p><%= link_to "Λεπτομέρειες »", lucky_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= link_to image_tag("results3.jpg", alt: "Rails"), 'tips' %>
          <h2>Προγνωστικά</h2>
          <p>Κείμενο για προγνωστικά.</p>
          <p><%= link_to "Λεπτομέρειες »", tips_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
</div>

app/views/layouts/_threecolumn2.html.erb
<!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
      <div class="visible-lg">
        <div class="col-lg-4">
        
         <iframe src="http://agones.gr/ticker_frontpages_show.php?width=220"
         width="220" height="286" scrolling=no marginwidth=0 marginheight=0 frameborder=0 border=0
         style="border:0;margin:0;padding:0;"></iframe><br />
         
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
                 
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          
            <iframe src="http://ticker.agones.gr/ticker2_vscroll_show.php?speed=1500&color=&color2=&bgcolor=363942&bgcolor2=ffffff&bgcolor1=efefef&font=11&width=250&height=250" width="250" height="250" scrolling=no marginwidth=0 marginheight=0 frameborder=0 border=0 style="border:0;margin:0;padding:0;"></iframe>
                
        </div><!-- /.col-lg-4 -->
        </div>
      </div><!-- /.row -->
</div>

app/views/layouts/_tv.html.erb
<!DOCTYPE html>
<html>
  
  <head data-gwd-animation-mode="quickMode">
    <link href="gwdyoutube_style.css" data-version="1" data-exports-type="gwd-youtube" rel="stylesheet">
    <script data-source="custom.elements.min.js" type="text/javascript" src="custom.elements.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <title>undefined</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="generator" content="Google Web Designer 1.1.1.0730">
    <style type="text/css">
      html, body {
        width: 100%;
        height: 100%;
        margin: 0px;
      }
      body {
        background-color: transparent;
        -webkit-transform: perspective(1400px) matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
        -webkit-transform-style: preserve-3d;
        width: 1920px;
        height: 1080px;
      }
      .gwd-img-1c8g {
        position: absolute;
        width: 640px;
        height: 540px;
        left: 0px;
        top: 0px;
      }
      .gwd-div-ivn5 {
        height: auto;
        left: 0px;
        position: absolute;
        top: 0px;
        width: auto;
      }
      .gwd-div-k18s {
        width: 0px;
        left: 639.8000000000002px;
        top: -0.3999999999998862px;
      }
      .gwd-img-ijy6 {
        width: 640px;
      }
      .gwd-div-ezdb {
        width: 0px;
        left: 0.05000000000021619px;
        top: 535.9500000000066px;
      }
      .gwd-img-lhkh {
        width: 640px;
      }
      .gwd-div-plxd {
        width: 0px;
        left: 640.2499999999923px;
        top: 535.7499999999997px;
      }
      .gwd-img-5fbk {
        width: 640px;
      }
      .gwd-div-zsr8 {
        left: 0px;
        top: 0px;
      }
      .gwd-div-r0ej {
        width: 0px;
        left: 1279.7500000000018px;
        top: -0.5500000000005px;
      }
      .gwd-img-33w5 {
        width: 640px;
      }
      .gwd-div-s9fd {
        width: 0px;
        left: 1279.6499999999987px;
        top: 535.6500000000003px;
      }
      .gwd-img-jigx {
        width: 640px;
      }
      .gwd-video-frdx {
        position: absolute;
        width: 290px;
        height: 156.5px;
        left: 492px;
        top: 329px;
      }
      .gwd-youtube-obmt {
        position: absolute;
        width: 200px;
        height: 140px;
        left: 782px;
        top: 486px;
      }
    </style>
    <script data-source="gwdyoutube_min.js" data-version="1" data-exports-type="gwd-youtube" type="text/javascript" src="gwdyoutube_min.js"></script>
  </head>
  
  <body>
    <div class="gwd-div-ivn5 gwd-div-zsr8">
      <%= link_to image_tag("991sta3.jpg", alt: "Rails", class: "gwd-img-1c8g"), 'lucky' %>
    </div>
    <div class="gwd-div-ivn5 gwd-div-ezdb">
    <%= link_to image_tag("991sta3.jpg", alt: "Rails", class: "gwd-img-1c8g gwd-img-lhkh"), 'lucky' %>
      
    </div>
    <div class="gwd-div-ivn5 gwd-div-plxd">
    <%= link_to image_tag("991sta3.jpg", alt: "Rails", class: "gwd-img-1c8g gwd-img-5fbk"), 'lucky' %>
      
    </div>
    <div class="gwd-div-ivn5 gwd-div-k18s">
    
    <div style="width:100%; height:100%; border:5px solid red; overflow:auto;">
  <video id="Video1"
  style="height:100%; width:100%; border:none;">
    <source src="http://playground.html5rocks.com/samples/html5_misc/chrome_japan.ogv"
      type='video/ogg; codecs="theora, vorbis"' />
    <source src="http://playground.html5rocks.com/samples/html5_misc/chrome_japan.webm"
      type='video/webm; codecs="vp8, vorbis"' />
    <source src="http://playground.html5rocks.com/samples/html5_misc/chrome_japan.mp4"
      type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"' />
  </video>
</div>

<div style="position:absolute; left:10px; top:10px;z-index:9999">
  <button id="StartButton">Start</button>
  <button id="PauseButton">Pause</button>
</div>

<script>

  var video = document.getElementById('Video1');
  $('#StartButton').on('click', function() {
    video.play();
  });

  $('#PauseButton').on('click', function() {
    video.pause();
  });

</script>

    </div>

    <div class="gwd-div-ivn5 gwd-div-k18s gwd-div-r0ej">
    <%= render 'shared/tips_feed' %>
    </div>
    <div class="gwd-div-ivn5 gwd-div-k18s gwd-div-s9fd">
    <%= link_to image_tag("991sta3.jpg", alt: "Rails", class: "gwd-img-1c8g gwd-img-ijy6 gwd-img-jigx"), 'lucky' %>
      
    </div>

    <video class="gwd-video-frdx" src="http://playground.html5rocks.com/samples/html5_misc/chrome_japan.ogv" controls="controls" autoplay="autoplay"></video>
  
  </body>

</html>

app/views/layouts/_tvover.html.erb
<!DOCTYPE html>
<html><head data-gwd-animation-mode="quickMode"><meta name="GCD" content="YTk3ODQ3ZWZhN2I4NzZmMzBkNTEwYjJl9542fabf8b2b62be62abaef6ddcdaa7c"/>
    <link href="gwdswipegallery_style.css" data-version="1" data-exports-type="gwd-swipegallery" rel="stylesheet">
    <link href="gwdgesture_style.css" data-version="1" data-exports-type="gwd-gesture" rel="stylesheet">
    <script data-source="custom.elements.min.js" type="text/javascript" src="custom.elements.min.js"></script>
    <title>Test</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="generator" content="Google Web Designer 1.1.2.0814">
    <style type="text/css">html, body {
  width: 100%;
  height: 100%;
  margin: 0px;
}

body {
  background-color: black;
  -webkit-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  -moz-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  -webkit-perspective: 1400px;
  -moz-perspective: 1400px;
  perspective: 1400px;
  -webkit-transform-style: preserve-3d;
  -moz-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.gwd-img-gg5g {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 230px;
  height: 200px;
}

.gwd-img-okgl {
  width: 45%;
  left: 55%;
  height: 45%;
  top: 0%;
}

.gwd-img-eb4t {
  top: 40%;
  width: 60%;
  height: 35%;
  left: 0%;
}

.gwd-img-qydm {
  top: 50%;
  width: 40%;
  left: 60%;
  height: 50%;
}

.gwd-img-468s {
  width: 50%;
  height: 40%;
  left: 0%;
  top: 0%;
}

.gwd-swipegallery-p238 {
  position: absolute;
  width: 200px;
  height: 140px;
  left: 600px;
  top: 199.6666666666684px;
}

</style>
    <script data-source="gwdgesture_min.js" data-version="1" data-exports-type="gwd-gesture" type="text/javascript" src="gwdgesture_min.js"></script>
    <script data-source="gwdimage_min.js" data-version="1" data-exports-type="gwd-image" type="text/javascript" src="gwdimage_min.js"></script>
    <script data-source="gwdpage_min.js" data-version="1" data-exports-type="gwd-page" type="text/javascript" src="gwdpage_min.js"></script>
    <script data-source="gwdswipegallery_min.js" data-version="1" data-exports-type="gwd-swipegallery" type="text/javascript" src="gwdswipegallery_min.js"></script>
  </head>
  
  <body id="body">
    <img class="gwd-img-gg5g gwd-img-468s" src=<%= @micropost.image %> alt="Avatar">

    <%= link_to image_tag("991sta2.jpg", alt: "Rails", class: "gwd-img-gg5g gwd-img-okgl"), 'lucky' %>
    
    <div class="gwd-img-gg5g gwd-img-eb4t">
      <%= render 'layouts/carousel' %>
    </div>

    <%= link_to image_tag("53b813b6b1948PTlmlbxvbAxfdYgIRaaL.png", alt: "Rails", class: "gwd-img-gg5g gwd-img-qydm"), 'lucky' %>
    
    
    
  

</body></html>

app/views/layouts/_tvover1.html.erb
<!DOCTYPE html>
<html><head data-gwd-animation-mode="quickMode"><meta name="GCD" content="YTk3ODQ3ZWZhN2I4NzZmMzBkNTEwYjJl9542fabf8b2b62be62abaef6ddcdaa7c"/>
    <link href="gwdswipegallery_style.css" data-version="1" data-exports-type="gwd-swipegallery" rel="stylesheet">
    <link href="gwdgesture_style.css" data-version="1" data-exports-type="gwd-gesture" rel="stylesheet">
    <script data-source="custom.elements.min.js" type="text/javascript" src="custom.elements.min.js"></script>
    <title>Test</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="generator" content="Google Web Designer 1.1.2.0814">
    <style type="text/css">html, body {
  width: 100%;
  height: 100%;
  margin: 0px;
}

body {
  background-color: black;
  -webkit-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  -moz-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
  -webkit-perspective: 1400px;
  -moz-perspective: 1400px;
  perspective: 1400px;
  -webkit-transform-style: preserve-3d;
  -moz-transform-style: preserve-3d;
  transform-style: preserve-3d;
}

.gwd-img-gg5g {
  position: absolute;
  left: 0px;
  top: 0px;
  width: 230px;
  height: 200px;
}

.gwd-img-okgl {
  width: 45%;
  left: 55%;
  height: 45%;
  top: 0%;
}

.gwd-img-eb4t {
  top: 40%;
  width: 50%;
  height: 25%;
  left: 5%;
}

.gwd-img-qydm {

  top: 30%;
  width: 40%;
  left: 60%;
  height: 70%;
}

.gwd-img-468s {
  width: 50%;
  height: 50%;
  left: 0%;
  top: 0%;
}


</style>
    <script data-source="gwdgesture_min.js" data-version="1" data-exports-type="gwd-gesture" type="text/javascript" src="gwdgesture_min.js"></script>
    <script data-source="gwdimage_min.js" data-version="1" data-exports-type="gwd-image" type="text/javascript" src="gwdimage_min.js"></script>
    <script data-source="gwdpage_min.js" data-version="1" data-exports-type="gwd-page" type="text/javascript" src="gwdpage_min.js"></script>
    <script data-source="gwdswipegallery_min.js" data-version="1" data-exports-type="gwd-swipegallery" type="text/javascript" src="gwdswipegallery_min.js"></script>
  </head>
  
  <body id="body">
    <img class="gwd-img-gg5g gwd-img-468s" src=<%= @micropost.image %> alt="Avatar">

    <%= link_to image_tag("991sta2.jpg", alt: "Rails", class: "gwd-img-gg5g gwd-img-okgl"), 'lucky' %>
    
    <div class="gwd-img-gg5g gwd-img-eb4t">
      <%= render 'layouts/carousel' %>
    </div>

    <div class="gwd-img-gg5g gwd-img-qydm">
      <%= render 'shared/banner' %>
    </div> 

</body></html>

app/views/layouts/_tvsimple.html.erb
<!DOCTYPE html>
<html>
  
  <head data-gwd-animation-mode="quickMode">
    <title>ok</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="generator" content="Google Web Designer 1.1.2.0814">
    <style type="text/css">
      html, body {
        width: 100%;
        height: 100%;
        margin: 0px;
      }
      body {
        background-color: black;
        -webkit-transform: perspective(1400px) matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);
        -webkit-transform-style: preserve-3d;
      }
      .gwd-div-156p {
        position: absolute;
        width: 960px;
        height: 640px;
        left: 0px;
        top: 0px;
      }
      .gwd-div-2m01 {
        position: absolute;
        width: 960px;
        height: 540px;
        left: 800px;
        top: 0px;
      }
      .gwd-div-ljr3 {
        position: absolute;
        width: 1280px;
        height: 540px;
        left: 0px;
        top: 640px;
      }
      .gwd-div-fvs8 {
        position: absolute;
        width: 960px;
        height: 540px;
        left: 960px;
        top: 540px;
      }
    </style>
  </head>
  
  <body>
    <div class="gwd-div-156p">
      <img class="avatar" src=<%= @micropost.image %> alt="Avatar">
      <p><%= @micropost.content %></p>
    </div>
    <div class="gwd-div-2m01">
      <%= link_to image_tag("991sta2.jpg", alt: "Rails", class: "gwd-img-1c8g gwd-img-lhkh"), 'lucky' %>
    </div>
    <div class="gwd-div-ljr3">
      <%= render 'layouts/carousel' %>
    </div>
    <div class="gwd-div-fvs8">
      <%= render 'shared/banner' %>
    </div>
  </body>

</html>


app/views/layouts/_twocolumn.html.erb
<!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Πρώτο μεγάλο άρθρο με εικόνα ή χωρίς\ <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor 
fringilla. Vestibulum id ligula porta felis euismod semper. Praesent 
commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, 
tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("results3.jpg", alt: "Rails"), 'http://rubyonrails.org/' %>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <%= link_to image_tag("results.jpg", alt: "Rails"), 'http://rubyonrails.org/' %>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor 
fringilla. Vestibulum id ligula porta felis euismod semper. Praesent 
commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, 
tellus ac cursus commodo.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor 
fringilla. Vestibulum id ligula porta felis euismod semper. Praesent 
commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, 
tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <%= link_to image_tag("results2.jpg", alt: "Rails"), 'http://rubyonrails.org/' %>
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
    </div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  

  <%= render 'layouts/shim' %>
</head>

  <body data-no-turbolink>
  	<%= render 'layouts/navbar' %>
    
    <%= yield %>
    <div class="container">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <!-- the same as above<div class="alert alert-<%= key %>"><%= value %></div>-->
      <% end %>
    </div>
    <%= render 'layouts/footer' %>
    <div class="footer">
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>